name: CI

on: [push]

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats:2.3.4
        ports:
          - "4222:4222"
    env:
      NATS_HOST: nats://localhost:4222
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
            command: test
            args: -- --nocapture
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
